---
- name: Install Jellyfin server
  hosts: jelly
  become: true

  tasks:
  - name: Set hostname
    hostname:
      name: pkg-jelly.int.cartathra.se

  - name: Open jellyfin ports
    firewalld:
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - 5666/tcp
      - 8096/tcp
      - 8920/tcp
      - 1900/udp
      - 7359/udp

  - name: Create scripts directory
    file:
      path: /root/bin
      state: directory
      owner: root
      group: root
      mode: '0700'

  - name: Copying newdownloads script
    copy:
      src: /root/ansible/files/bin/newdownloads.py
      dest: /root/bin/newdownloads.py
      owner: root
      group: root
      mode: '0700'

  - name: Copying plexautoupdate script
    copy:
      src: /root/ansible/files/bin/plexautoupdate.sh
      dest: /root/bin/plexautoupdate.sh
      owner: root
      group: root
      mode: '0700'

  - name: Installing RPMFusion Repository
    dnf:
      name: "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm"
      state: present
      disable_gpg_check: yes

  - name: Installing other packages
    dnf:
      name: "{{ item }}"
      state: present
      enablerepo: powertools
    loop:
      - python3
      - python3-libsemanage
      - glibc-langpack-en
      - nrpe
      - nagios-plugins
      - nfs-utils
      - epel-release
      - ffmpeg

  - name: Install Jellyfin rpm
    dnf:
      name: "https://repo.jellyfin.org/releases/server/centos/stable/{{ item }}"
      state: present
      disable_gpg_check: yes
    loop:
      - server/jellyfin-server-10.6.4-1.el7.x86_64.rpm
      - web/jellyfin-web-10.6.4-1.el7.noarch.rpm

  - name: Copying nrpe config
    copy:
      src: /root/ansible/files/nrpe/nrpe.cfg
      dest: /etc/nagios/nrpe.cfg
      force: yes
      owner: root
      group: root

  - name: Mounting Primary Media Library
    mount:
      fstype: nfs
      src: <nas-ip>:/volume1/Mediacenter
      path: /mnt/nas/media
      state: mounted

  - name: Mounting Secondary Media Library
    mount:
      fstype: nfs
      src: <nas2-ip>:/volume1/Mediacenter
      path: /mnt/nas/media2
      state: mounted

  - name: Mounting USB1 Media Library
    mount:
      fstype: nfs
      src: <nas-ip>:/share/USB1
      path: /mnt/nas/usb
      state: mounted

  - name: Mounting USB2 Media Library
    mount:
      fstype: nfs
      src: <nas-ip>:/share/USB2-2
      path: /mnt/nas/usb2
      state: mounted

  - name: Configuring SELinux
    seboolean:
      name: httpd_can_network_connect
      persistent: yes
      state: yes

  - name: Starting services
    service:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    loop:
      - nrpe
      - jellyfin
