---
- name: Install Nginx & php server
  hosts: Nginx
  become: true

  - name: Open ports
    firewalld:
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - 5666/tcp
      - 80/tcp
      - 443/tcp

  - name: Create scripts directory
    file:
      path: /root/bin
      state: directory
      owner: root
      group: root
      mode: '0700'

  - name: Installing other packages
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - python3
      - python3-libsemanage
      - epel-release
      - unzip
      - tar
      - bzip2
      - nginx
      - php
      - php-mysqlnd
      - php-fpm
      - php-opcache
      - php-common
      - php-gd
      - php-json
      - php-curl
      - php-zip
      - php-xml
      - php-mbstring
      - php-bz2
      - php-intl
      - glibc-langpack-en
      - nrpe
      - nagios-plugins
      - nfs-utils
      - dnf-utils

  - name: Copying nginx config
    copy:
      src: /root/ansible/files/nextcloud/nextcloud.conf
      dest: /etc/nginx/conf.d/nextcloud.conf
      force: yes
      owner: root
      group: root
      mode: '0644'

  - name: Replace php-fpm user
    lineinfile:
      path: /etc/php-fpm.d/www.conf
      regexp: ^user
      line: 'user = nginx'
      owner: root
      group: root
      mode: '0644'

  - name: Replace php-fpm group
    lineinfile:
      path: /etc/php-fpm.d/www.conf
      regexp: ^group
      line: 'group = nginx'
      owner: root
      group: root
      mode: '0644'

  - name: Set download size in php.ini
    lineinfile:
      path: /etc/php.ini
      regexp: ^upload_max_filesize
      line: 'upload_max_filesize = 1024M'
      owner: root
      group: root
      mode: '0644'

  - name: Let nginx user access php libraries
    acl:
      path: "{{ item }}"
      entity: nginx
      etype: user
      permissions: rwx
      default: yes
      state: present
      recursive: yes
    loop:
      - /var/lib/php/opcache/
      - /var/lib/php/session/
      - /var/lib/php/wsdlcache/

  - name: Copying server certificate
    copy:
      src: /root/ansible/files/server.crt
      dest: /etc/pki/tls/certs/server.crt
      force: yes
      owner: root
      group: root
      mode: '0644'

  - name: Copying server key
    copy:
      src: /root/ansible/files/server.key
      dest: /etc/pki/tls/private/server.key
      force: yes
      owner: root
      group: root
      mode: '0644'

  - name: Copying nrpe config
    copy:
      src: /root/ansible/files/nrpe/nrpe.cfg
      dest: /etc/nagios/nrpe.cfg
      force: yes
      owner: root
      group: root

  - name: Configuring SELinux
    seboolean:
      name: "{{ item }}"
      persistent: yes
      state: yes
    loop:
      - httpd_execmem
      - httpd_can_network_connect

  - name: Starting services
    service:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    loop:
      - firewalld
      - nrpe
      - nginx
      - php-fpm
